"""
This type stub file was generated by pyright.
"""

from collections.abc import Iterable, Iterator
from typing import Any, Self

"""
This type stub file was generated by pyright.
"""
class DecksNotWrittenException(Exception):
  """Gaggle exception for failure to write all stored Decks to file. Can return
  the last successfully written deck"""
  def __init__(self, last_deck_written: int | None = ...) -> None:
    """
    Args:
      last_deck_written: An int representing the index of the last deck
      successfully written to file. None if no success writes occurred.
    """
    ...
  
  def __str__(self) -> str:
    ...
  


class DuplicateWarning(Warning):
  """Gaggle warning when attempting to use a duplicate value when a unique value
  is expected. However, a replacement value can be generated at run time.
  Warning informs of the value used as a replacement."""
  def __init__(self, context_message: Any, duplicate_value: Any, replacement_value: Any) -> None:
    """
    Args:
      context_message: Used to provide context to duplicate values. See
      documentation for DuplicateWarning._create_message() for further detail
      duplicate_value: The value which should have been unique
      replacement_value: The value which will be used as a replacement for the
        duplicate
    """
    ...
  
  def __str__(self) -> str:
    ...
  


class LeftoverArgumentWarning(Warning):
  """Gaggle warning when extra arguments remain after a function call. The extra
  arguments were not necessary to successfully complete the function call."""
  def __init__(self, context_message: Any, leftovers: Iterable[Any], leftover_name: Any) -> None:
    ...
  
  def __str__(self) -> str:
    ...
  
  @classmethod
  def from_iterable(cls, context_message: str, iterable: Iterable[Any], leftover_name: str, delimiter: str = ...) -> Self:
    """Formats an iterable to be used in LeftoverArgumentWarning. The values of
    iterable are recommended to have defined __str__() formats.

    For information on how the context_message, iterable, and leftover_name are
    used, see documentation for LeftoverArgumentWarning._create_message().

    Args:
      context_message: Gives information on the parameter for which excess
      arguments were passed.
      iterable: Each value is cast into a string and joined using delimiter.
      leftover_name: An informative name. Output stream facing.
      delimiter: The delimiter by which all values in iterable are joined into
      one string.

    Returns:
      A LeftoverArgumentWarning composed of passed arguments.
    """
    ...
  
  @classmethod
  def from_iterator(cls, iterator: Iterator[Any], **kwargs: str) -> Self:
    """Warning, this function exhausts the iterator.

    Helper function of LeftoverArgumentWarning.from_iterable(). Formats
    iterator as an iterable.

    See LeftoverArgumentWarning.from_iterable() documentation for more detail.

    Args:
      iterator: An iterator processed into a list. Exhausted.
      kwargs: Keyword arguments as specified by
        LeftoverArgumentWarning.from_iterable()

    Returns:
      A LeftoverArgumentWarning composed of passed arguments.
    """
    ...
  
  @classmethod
  def from_values(cls, *values: Iterable[Any], **kwargs: str) -> Self:
    """Helper function of LeftoverArgumentWarning.from_iterable(). Creates a
    chain of each value in values. This is equivalent to flattening each value
    in values by one layer and combining the result into one iterable.

    See LeftoverArgumentWarning.from_iterable() documentation for more detail.

    Args:
      *values: Iterables to be chained. Unpacked as separate arguments.
      **kwargs: Keyword arguments as specified by
        LeftoverArgumentWarning.from_iterable()

    Examples:
      >>> LeftoverArgumentWarning.from_values([1, 2, '3'], 'hi', ['32'], ...)
      formats *values as an iterable where next() returns:

      1 -> 2 -> '3' -> 'h' -> 'i' -> '32'

    Returns:
      A LeftoverArgumentWarning composed of passed arguments.
    """
    ...
  


